import { ME_ID } from "./constants";
import type { Post, User } from "./types";

export const USERS: User[] = [
  {
    id: ME_ID,
    name: "Qraft 太郎",
    handle: "aha_taro",
    bio: "数式でドパミンを搾り取る人。21:00は宗教。",
    school: "明星高専 2年B組",
    avatar: "🧠",
    banner: "from-[#2e1065] via-[#000] to-[#365314]",
    accent: "#A855F7",
    tiers: { math: 3, physics: 2, chemistry: 2 },
    age: 17,
    stats: { calc: 72, insight: 81, proof: 64 },
    followerCount: 128,
    followingCount: 40,
    titles: ["PULSEの求道者", "初回Qraft達成"],
    activeTitles: ["PULSEの求道者", "初回Qraft達成"],
    analytics: [
      { day: "月", solves: 3, aha: 4.2 },
      { day: "火", solves: 5, aha: 3.8 },
      { day: "水", solves: 2, aha: 4.9 },
      { day: "木", solves: 6, aha: 4.1 },
      { day: "金", solves: 4, aha: 4.6 },
      { day: "土", solves: 8, aha: 4.8 },
      { day: "日", solves: 7, aha: 5.0 },
    ],
  },
  {
    id: "u-official",
    name: "Qraft Official",
    handle: "aha_official",
    bio: "毎日21:00、全国一斉の10分一本勝負。",
    school: "Qraft HQ",
    avatar: "🔥",
    banner: "from-[#365314] via-[#000] to-[#6b21a8]",
    accent: "#CCFF00",
    tiers: { math: 5, physics: 5, chemistry: 5 },
    age: null,
    stats: { calc: 99, insight: 99, proof: 99 },
    followerCount: 120400,
    followingCount: 0,
    titles: ["PULSEホスト"],
    activeTitles: ["PULSEホスト"],
    verified: true,
    isVerified: true,
    analytics: [],
  },
  {
    id: "u-mirai",
    name: "理依 みらい",
    handle: "mirai_ri",
    bio: "証明は短く、快感は長く。数オリ出身。",
    school: "筑波大附属駒場 3年",
    avatar: "✨",
    banner: "from-[#4c1d95] via-[#0f172a] to-[#1e1b4b]",
    accent: "#A855F7",
    tiers: { math: 5, physics: 4, chemistry: 3 },
    age: 18,
    stats: { calc: 94, insight: 96, proof: 98 },
    followerCount: 8420,
    followingCount: 112,
    titles: ["殿堂入り解法 x12", "ドパミンの神"],
    activeTitles: ["殿堂入り解法 x12", "ドパミンの神"],
    verified: true,
    isVerified: true,
    analytics: [
      { day: "月", solves: 9, aha: 4.9 },
      { day: "火", solves: 8, aha: 4.7 },
      { day: "水", solves: 11, aha: 5.0 },
      { day: "木", solves: 7, aha: 4.8 },
      { day: "金", solves: 10, aha: 4.9 },
      { day: "土", solves: 12, aha: 5.0 },
      { day: "日", solves: 9, aha: 4.6 },
    ],
  },
  {
    id: "u-ken",
    name: "数式ケン",
    handle: "ken_formula",
    bio: "計算力で殴る。エレガントさは後からついてくる。",
    school: "開成高校 2年A組",
    avatar: "📐",
    banner: "from-[#164e63] via-[#000] to-[#1e3a8a]",
    accent: "#22D3EE",
    tiers: { math: 4, physics: 3, chemistry: 2 },
    age: 16,
    stats: { calc: 97, insight: 70, proof: 78 },
    followerCount: 2310,
    followingCount: 89,
    titles: ["方程式ストライカー+"],
    activeTitles: ["方程式ストライカー+"],
    analytics: [],
  },
  {
    id: "u-alice",
    name: "電磁アリス",
    handle: "alice_em",
    bio: "Maxwell 方程式を子守唄にしている。",
    school: "灘高校 3年",
    avatar: "⚡",
    banner: "from-[#1e3a8a] via-[#000] to-[#581c87]",
    accent: "#818CF8",
    tiers: { math: 4, physics: 5, chemistry: 3 },
    age: 19,
    stats: { calc: 88, insight: 92, proof: 85 },
    followerCount: 5102,
    followingCount: 201,
    titles: ["アインシュタインの再来", "波動マスター"],
    activeTitles: ["アインシュタインの再来", "波動マスター"],
    analytics: [],
  },
  {
    id: "u-yu",
    name: "有機ユウ",
    handle: "yu_organic",
    bio: "矢印を美しく描けば分子は踊る。",
    school: "東京工業大学 1年",
    avatar: "🧪",
    banner: "from-[#14532d] via-[#000] to-[#713f12]",
    accent: "#84CC16",
    tiers: { math: 2, physics: 3, chemistry: 5 },
    age: 17,
    stats: { calc: 68, insight: 90, proof: 74 },
    followerCount: 3901,
    followingCount: 155,
    titles: ["錬金術の神", "殿堂入りクイズ x4"],
    activeTitles: ["錬金術の神", "殿堂入りクイズ x4"],
    analytics: [],
  },
  {
    id: "u-ren",
    name: "波動レン",
    handle: "ren_wave",
    bio: "干渉縞よりタイムラインの方が賑やか。",
    school: "明星高専 3年A組",
    avatar: "🌊",
    banner: "from-[#0e7490] via-[#000] to-[#1e1b4b]",
    accent: "#22D3EE",
    tiers: { math: 3, physics: 4, chemistry: 3 },
    age: 20,
    stats: { calc: 80, insight: 84, proof: 77 },
    followerCount: 980,
    followingCount: 300,
    titles: ["力学ストライカー"],
    activeTitles: ["力学ストライカー"],
    analytics: [],
  },
];

export const USER_MAP = Object.fromEntries(USERS.map((u) => [u.id, u]));

export const INITIAL_FOLLOWS: string[] = ["u-mirai", "u-official", "u-alice"];
export const INITIAL_FOLLOWERS: string[] = ["u-ken", "u-yu", "u-ren", "u-mirai"];

export const POSTS: Post[] = [
  {
    id: "p1",
    authorId: "u-mirai",
    kind: "problem",
    subject: "math",
    text: "正の実数 $a,b,c$ が $a+b+c=abc$ を満たす。\n\n$$\\sum_{cyc}\\frac{1}{a^2+1}$$ の最大値は？\n\nヒント: $a=\\tan A$ は罠。もっと甘い置換がある。",
    createdAt: "2026-08-29T18:12:00",
    replyCount: 42,
    repostCount: 18,
    likeCount: 512,
    ahaSum: 4.9 * 86,
    ahaCount: 86,
    eleganceSum: 0,
    eleganceCount: 0,
  },
  {
    id: "p2",
    authorId: "u-alice",
    kind: "problem",
    subject: "physics",
    text: "一様磁場 $B$ 中を速度 $v$ で進む導体棒。レールの抵抗を無視し、棒だけ $R$。\n\n誘導電流が磁場から受ける力は $F=-\\frac{B^2\\ell^2 v}{R}$。\n\n**問い:** 失われた運動エネルギーはすべてジュール熱か？ ラグランジアンで示せ。",
    createdAt: "2026-08-29T16:40:00",
    replyCount: 21,
    repostCount: 9,
    likeCount: 301,
    ahaSum: 4.6 * 44,
    ahaCount: 44,
    eleganceSum: 0,
    eleganceCount: 0,
  },
  {
    id: "p3",
    authorId: "u-ken",
    kind: "solution",
    subject: "math",
    problemId: "p1",
    text: "みらいさんの問題、置換 $a=x+\\frac{1}{x}$ で一発。手書きで置いておく。",
    createdAt: "2026-08-29T19:02:00",
    replyCount: 11,
    repostCount: 7,
    likeCount: 220,
    ahaSum: 0,
    ahaCount: 0,
    eleganceSum: 4.8 * 61,
    eleganceCount: 61,
    solutionFormat: "handwriting",
    pages: [
      { id: "n1", latex: "a=x+\\dfrac{1}{x}\\;\\Rightarrow\\; a+b+c=abc", doodle: 1 },
      { id: "n2", latex: "\\sum \\dfrac{1}{a^2+1}=\\dfrac{3}{2}", doodle: 2 },
    ],
  },
  {
    id: "p3t",
    authorId: "u-mirai",
    kind: "solution",
    subject: "math",
    problemId: "p1",
    solutionFormat: "typed",
    text: "## 方針\n$a=x+\\frac{1}{x}$ と置くと $a+b+c=abc$ がきれいになる。\n\n$$\\sum_{cyc}\\frac{1}{a^2+1}=\\frac{3}{2}$$\n\n**検算** は $a=b=c=\\sqrt{3}$。\n\n```python\nprint(3 / 2)\n```",
    createdAt: "2026-08-29T19:40:00",
    replyCount: 5,
    repostCount: 4,
    likeCount: 88,
    ahaSum: 0,
    ahaCount: 0,
    eleganceSum: 4.7 * 22,
    eleganceCount: 22,
  },
  {
    id: "p4",
    authorId: "u-yu",
    kind: "problem",
    subject: "chemistry",
    text: "アセト酢酸エチルのケト-エノール。極性溶媒でケトが勝つのはなぜ？\n\n$$K=\\frac{[enol]}{[keto]}$$ を DMSO vs MeOH で qualitatively 説明せよ。水素結合ネットワークが鍵。",
    createdAt: "2026-08-29T12:08:00",
    replyCount: 16,
    repostCount: 5,
    likeCount: 188,
    ahaSum: 4.7 * 39,
    ahaCount: 39,
    eleganceSum: 0,
    eleganceCount: 0,
  },
  {
    id: "p5",
    authorId: "u-ren",
    kind: "solution",
    subject: "physics",
    problemId: "p2",
    text: "エネルギー収支は磁場の仕事まで入れないと閉じない。キャンバス2枚。",
    createdAt: "2026-08-29T17:22:00",
    replyCount: 4,
    repostCount: 2,
    likeCount: 96,
    ahaSum: 0,
    ahaCount: 0,
    eleganceSum: 4.4 * 28,
    eleganceCount: 28,
    pages: [
      { id: "n3", latex: "P_{em}=I\\ell v B=\\frac{B^2\\ell^2 v^2}{R}", doodle: 3 },
      { id: "n4", latex: "P_{J}=I^2R=P_{em}", doodle: 0 },
    ],
  },
  {
    id: "p6",
    authorId: "u-mirai",
    kind: "solution",
    subject: "math",
    problemId: "sprint-legend",
    text: "トレミーを使わず、三角比の積和だけで対角線を閉じた。これがエレガント。",
    createdAt: "2026-08-28T21:08:00",
    replyCount: 58,
    repostCount: 40,
    likeCount: 1204,
    ahaSum: 0,
    ahaCount: 0,
    eleganceSum: 5.0 * 190,
    eleganceCount: 190,
    pages: [
      { id: "n5", latex: "\\cos C=\\frac{a^2+b^2-c^2}{2ab}", doodle: 2 },
      { id: "n6", latex: "AC=\\sqrt{\\frac{abcd(ab+cd)}{(ac+bd)(ad+bc)}}", doodle: 1 },
      { id: "n7", latex: "検算:\\; 3,4,5,6 \\Rightarrow AC=\\sqrt{18.2}", doodle: 4 },
    ],
  },
  {
    id: "p7",
    authorId: "u-alice",
    kind: "problem",
    subject: "physics",
    text: "光子の運動量 $p=E/c$。太陽光を帆で受けるとき、反射率 $r$ の輻射圧は\n\n$$P=\\frac{I}{c}(1+r)$$\n\n完全吸収と完全反射、加速度は何倍違う？ 質量 $m$、面積 $A$。",
    createdAt: "2026-08-28T09:30:00",
    replyCount: 33,
    repostCount: 12,
    likeCount: 410,
    ahaSum: 4.3 * 70,
    ahaCount: 70,
    eleganceSum: 0,
    eleganceCount: 0,
  },
  {
    id: "p8",
    authorId: "u-yu",
    kind: "solution",
    subject: "chemistry",
    problemId: "p4",
    text: "エノールは分子内水素結合。MeOH はそれを壊しに来る。矢印機構3ページ。",
    createdAt: "2026-08-29T13:10:00",
    replyCount: 9,
    repostCount: 6,
    likeCount: 274,
    ahaSum: 0,
    ahaCount: 0,
    eleganceSum: 4.9 * 80,
    eleganceCount: 80,
    pages: [
      { id: "n8", latex: "\\mathrm{keto}\\rightleftharpoons\\mathrm{enol}", doodle: 1 },
      { id: "n9", latex: "\\Delta G = -RT\\ln K", doodle: 3 },
    ],
  },
  {
    id: "p9",
    authorId: ME_ID,
    kind: "problem",
    subject: "math",
    text: "初投稿。$n$ を自然数として $$\\sum_{k=1}^n k^3 = \\left(\\sum_{k=1}^n k\\right)^2$$ を組み合わせで説明したい。正方形タイルの気持ち。",
    createdAt: "2026-08-27T21:44:00",
    replyCount: 8,
    repostCount: 3,
    likeCount: 67,
    ahaSum: 4.1 * 14,
    ahaCount: 14,
    eleganceSum: 0,
    eleganceCount: 0,
  },
  {
    id: "p10",
    authorId: "u-ken",
    kind: "problem",
    subject: "math",
    text: "行列 $A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$。$A^n$ を求め、$$e^{tA}$$ まで一気に書け。ジョルダン細胞の気持ちを手で味わえ。",
    createdAt: "2026-08-26T11:00:00",
    replyCount: 19,
    repostCount: 8,
    likeCount: 155,
    ahaSum: 4.5 * 32,
    ahaCount: 32,
    eleganceSum: 0,
    eleganceCount: 0,
  },
];

export const MOCK_REPLIES: Post[] = [
  {
    id: "r-p1-1",
    authorId: "u-alice",
    kind: "reply",
    subject: "math",
    replyToId: "p1",
    text: "置換 $a=\\tan A$ は罠、同意。$a=x+1/x$ が見えなかった。",
    createdAt: "2026-08-29T18:40:00",
    replyCount: 0,
    repostCount: 0,
    likeCount: 4,
    ahaSum: 0,
    ahaCount: 0,
    eleganceSum: 0,
    eleganceCount: 0,
  },
  {
    id: "r-p1-2",
    authorId: "u-ken",
    kind: "reply",
    subject: "math",
    replyToId: "p1",
    text: "最大値 $3/2$ で合ってる？検算した。",
    createdAt: "2026-08-29T18:55:00",
    replyCount: 0,
    repostCount: 0,
    likeCount: 2,
    ahaSum: 0,
    ahaCount: 0,
    eleganceSum: 0,
    eleganceCount: 0,
  },
  {
    id: "r-p2-1",
    authorId: "u-ren",
    kind: "reply",
    subject: "physics",
    replyToId: "p2",
    text: "磁場の仕事を忘れるとエネルギーが合わない、そこがわかった瞬間。",
    createdAt: "2026-08-29T16:58:00",
    replyCount: 0,
    repostCount: 0,
    likeCount: 6,
    ahaSum: 0,
    ahaCount: 0,
    eleganceSum: 0,
    eleganceCount: 0,
  },
];

export function communityForDay(dayId: string): Post[] {
  return [
    {
      id: `c-${dayId}-1`,
      authorId: "u-mirai",
      kind: "solution",
      subject: "math",
      sprintDay: dayId,
      text: "10分切り。対角線は余弦の差で閉じた。",
      createdAt: `${dayId}T21:06:12`,
      replyCount: 14,
      repostCount: 9,
      likeCount: 340,
      ahaSum: 0,
      ahaCount: 0,
      eleganceSum: 4.9 * 72,
      eleganceCount: 72,
      pages: [
        { id: "c1", latex: "\\text{Step 1. 対角で分割}", doodle: 2 },
        { id: "c2", latex: "x^2=\\frac{(ac+bd)(ad+bc)}{ab+cd}", doodle: 1 },
      ],
    },
    {
      id: `c-${dayId}-2`,
      authorId: "u-ken",
      kind: "solution",
      subject: "math",
      sprintDay: dayId,
      text: "計算力ゴリ押し。数値代入してから一般化。",
      createdAt: `${dayId}T21:09:40`,
      replyCount: 3,
      repostCount: 1,
      likeCount: 88,
      ahaSum: 0,
      ahaCount: 0,
      eleganceSum: 3.9 * 20,
      eleganceCount: 20,
      pages: [{ id: "c3", latex: "AC\\approx 4.266", doodle: 4 }],
    },
    {
      id: `c-${dayId}-3`,
      authorId: "u-alice",
      kind: "solution",
      subject: "physics",
      sprintDay: dayId,
      text: "物理寄りの解釈。保存量に気づくと1分で終わる。",
      createdAt: `${dayId}T21:04:01`,
      replyCount: 7,
      repostCount: 4,
      likeCount: 190,
      ahaSum: 0,
      ahaCount: 0,
      eleganceSum: 4.6 * 40,
      eleganceCount: 40,
      pages: [{ id: "c4", latex: "T=4\\sqrt{\\frac{\\ell}{g}}K(\\sin\\tfrac{\\theta_0}{2})", doodle: 0 }],
    },
  ];
}

export const RIVAL_ACTIVITY = [
  { id: "a1", userId: "u-mirai", text: "全国戦を 4:12 で提出。精度 98%。", time: "2分前" },
  { id: "a2", userId: "u-alice", text: "あなたの解法にエレガント度 ★★★★★", time: "18分前" },
  { id: "a3", userId: "u-yu", text: "フォローされました", time: "1時間前" },
  { id: "a4", userId: "u-ken", text: "脳汁いいね ×12 をあなたの問題に投下", time: "3時間前" },
  { id: "a5", userId: "u-ren", text: "ライバル申請（週次勝率で勝負）", time: "昨日" },
];
