import { ME_ID } from "./constants";
import type { Post, User } from "./types";

export const USERS: User[] = [
  {
    id: ME_ID,
    name: "Qraft 太郎",
    handle: "aha_taro",
    bio: "数式でドパミンを搾り取る人。21:00は宗教。",
    school: "明星高専 2年B組",
    avatar: "🧠",
    banner: "from-[#2e1065] via-[#000] to-[#365314]",
    accent: "#A855F7",
    tiers: { math: 3, physics: 2, chemistry: 2 },
    age: 17,
    stats: { calc: 72, insight: 81, proof: 64 },
    followerCount: 128,
    followingCount: 40,
    titles: ["PULSEの求道者", "初回Qraft達成"],
    activeTitles: ["PULSEの求道者", "初回Qraft達成"],
    analytics: [
      { day: "月", solves: 3, aha: 4.2 },
      { day: "火", solves: 5, aha: 3.8 },
      { day: "水", solves: 2, aha: 4.9 },
      { day: "木", solves: 6, aha: 4.1 },
      { day: "金", solves: 4, aha: 4.6 },
      { day: "土", solves: 8, aha: 4.8 },
      { day: "日", solves: 7, aha: 5.0 },
    ],
  },
  {
    id: "u-official",
    name: "Qraft Official",
    handle: "qraft",
    bio: "毎日21:00、全国一斉の10分一本勝負。",
    school: "Qraft HQ",
    avatar: "🔥",
    banner: "from-[#365314] via-[#000] to-[#6b21a8]",
    accent: "#CCFF00",
    tiers: { math: 5, physics: 5, chemistry: 5 },
    age: null,
    stats: { calc: 99, insight: 99, proof: 99 },
    followerCount: 120400,
    followingCount: 0,
    titles: ["PULSEホスト"],
    activeTitles: ["PULSEホスト"],
    verified: true,
    isVerified: true,
    analytics: [],
  },
  {
    id: "u-mirai",
    name: "理依 みらい",
    handle: "mirai_ri",
    bio: "証明は短く、快感は長く。数オリ出身。",
    school: "筑波大附属駒場 3年",
    avatar: "✨",
    banner: "from-[#4c1d95] via-[#0f172a] to-[#1e1b4b]",
    accent: "#A855F7",
    tiers: { math: 5, physics: 4, chemistry: 3 },
    age: 18,
    stats: { calc: 94, insight: 96, proof: 98 },
    followerCount: 8420,
    followingCount: 112,
    titles: ["殿堂入り解法 x12", "ドパミンの神"],
    activeTitles: ["殿堂入り解法 x12", "ドパミンの神"],
    verified: true,
    isVerified: true,
    analytics: [
      { day: "月", solves: 9, aha: 4.9 },
      { day: "火", solves: 8, aha: 4.7 },
      { day: "水", solves: 11, aha: 5.0 },
      { day: "木", solves: 7, aha: 4.8 },
      { day: "金", solves: 10, aha: 4.9 },
      { day: "土", solves: 12, aha: 5.0 },
      { day: "日", solves: 9, aha: 4.6 },
    ],
  },
  {
    id: "u-ken",
    name: "数式ケン",
    handle: "ken_formula",
    bio: "計算力で殴る。エレガントさは後からついてくる。",
    school: "開成高校 2年A組",
    avatar: "📐",
    banner: "from-[#164e63] via-[#000] to-[#1e3a8a]",
    accent: "#22D3EE",
    tiers: { math: 4, physics: 3, chemistry: 2 },
    age: 16,
    stats: { calc: 97, insight: 70, proof: 78 },
    followerCount: 2310,
    followingCount: 89,
    titles: ["方程式ストライカー+"],
    activeTitles: ["方程式ストライカー+"],
    analytics: [],
  },
  {
    id: "u-alice",
    name: "電磁アリス",
    handle: "alice_em",
    bio: "Maxwell 方程式を子守唄にしている。",
    school: "灘高校 3年",
    avatar: "⚡",
    banner: "from-[#1e3a8a] via-[#000] to-[#581c87]",
    accent: "#818CF8",
    tiers: { math: 4, physics: 5, chemistry: 3 },
    age: 19,
    stats: { calc: 88, insight: 92, proof: 85 },
    followerCount: 5102,
    followingCount: 201,
    titles: ["アインシュタインの再来", "波動マスター"],
    activeTitles: ["アインシュタインの再来", "波動マスター"],
    analytics: [],
  },
  {
    id: "u-yu",
    name: "有機ユウ",
    handle: "yu_organic",
    bio: "矢印を美しく描けば分子は踊る。",
    school: "東京工業大学 1年",
    avatar: "🧪",
    banner: "from-[#14532d] via-[#000] to-[#713f12]",
    accent: "#84CC16",
    tiers: { math: 2, physics: 3, chemistry: 5 },
    age: 17,
    stats: { calc: 68, insight: 90, proof: 74 },
    followerCount: 3901,
    followingCount: 155,
    titles: ["錬金術の神", "殿堂入りクイズ x4"],
    activeTitles: ["錬金術の神", "殿堂入りクイズ x4"],
    analytics: [],
  },
  {
    id: "u-ren",
    name: "波動レン",
    handle: "ren_wave",
    bio: "干渉縞よりタイムラインの方が賑やか。",
    school: "明星高専 3年A組",
    avatar: "🌊",
    banner: "from-[#0e7490] via-[#000] to-[#1e1b4b]",
    accent: "#22D3EE",
    tiers: { math: 3, physics: 4, chemistry: 3 },
    age: 20,
    stats: { calc: 80, insight: 84, proof: 77 },
    followerCount: 980,
    followingCount: 300,
    titles: ["力学ストライカー"],
    activeTitles: ["力学ストライカー"],
    analytics: [],
  },
];

export const USER_MAP = Object.fromEntries(USERS.map((u) => [u.id, u]));

export const INITIAL_FOLLOWS: string[] = ["u-official"];
export const INITIAL_FOLLOWERS: string[] = [];

export const POSTS: Post[] = [];

export const MOCK_REPLIES: Post[] = [];

export function communityForDay(_dayId: string): Post[] {
  return [];
}

export const RIVAL_ACTIVITY = [
  { id: "a1", userId: "u-mirai", text: "全国戦を 4:12 で提出。精度 98%。", time: "2分前" },
  { id: "a2", userId: "u-alice", text: "あなたの解法にエレガント度 ★★★★★", time: "18分前" },
  { id: "a3", userId: "u-yu", text: "フォローされました", time: "1時間前" },
  { id: "a4", userId: "u-ken", text: "脳汁いいね ×12 をあなたの問題に投下", time: "3時間前" },
  { id: "a5", userId: "u-ren", text: "ライバル申請（週次勝率で勝負）", time: "昨日" },
];
